[install]
is_configured = 0
state = enabled
build = 1

[id]
name = REPLACE_APP_ID
version = 1.0.0

[launcher]
author = REPLACE_AUTHOR
description = REPLACE_DESCRIPTION
version = 1.0.0

[package]
id = REPLACE_APP_ID

[ui]
is_visible = true
label = REPLACE_LABEL
