[stigkvreconcile]
filename = stigkvreconcile.py
type = python
python.version = python3
python.required = 3.9, 3.13
streaming = false

[stigkvreviewaging]
filename = stigkvreviewaging.py
type = python
python.version = python3
python.required = 3.9, 3.13
streaming = false
