[stigkvreconcile]
filename = stigkvreconcile.py
type = python
python.version = python3
streaming = false

[stigkvreviewaging]
filename = stigkvreviewaging.py
type = python
python.version = python3
streaming = false
