[stig]
homePath   = $SPLUNK_DB/stig/db
coldPath   = $SPLUNK_DB/stig/colddb
thawedPath = $SPLUNK_DB/stig/thaweddb
frozenTimePeriodInSecs = 31536000
repFactor = auto

[stig_audit]
homePath   = $SPLUNK_DB/stig_audit/db
coldPath   = $SPLUNK_DB/stig_audit/colddb
thawedPath = $SPLUNK_DB/stig_audit/thaweddb
frozenTimePeriodInSecs = 31536000
repFactor = auto
