[stig:finding]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = none
INDEXED_EXTRACTIONS = json
CHARSET = UTF-8
TIMESTAMP_FIELDS = time
TZ = UTC
TRUNCATE = 0

[stig:audit]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = none
INDEXED_EXTRACTIONS = json
CHARSET = UTF-8
TIMESTAMP_FIELDS = time
TZ = UTC
TRUNCATE = 0
